version: '3.8'

services:
  web:
    build: .
    environment:
      - APP_CONFIG_FILE=local
    command: uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8008:8000